### ISSUE TITLE
cannot install via npm

### ISSUE THREAD

**Issue by bertsky** [kba/makefile-parser#10]
```
npm ERR! Linux 4.15.0-72-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@kba/makefile-parser"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

<details><summary>npm-debug.log</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@kba/makefile-parser' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @kba/makefile-parser
8 silly fetchNamedPackageData @kba/makefile-parser
9 silly mapToRegistry name @kba/makefile-parser
10 silly mapToRegistry scope (from package name) @kba
11 verbose mapToRegistry no registry URL found in name for scope @kba
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/@kba%2fmakefile-parser
15 verbose request uri https://registry.npmjs.org/@kba%2fmakefile-parser
16 verbose request no auth needed
17 info attempt registry request try #1 at 20:36:14
18 verbose request id d630b04d52f650c0
19 http request GET https://registry.npmjs.org/@kba%2fmakefile-parser
20 http 200 https://registry.npmjs.org/@kba%2fmakefile-parser
21 verbose headers { date: 'Thu, 11 Nov 2021 19:36:15 GMT',
21 verbose headers   'content-type': 'application/json',
21 verbose headers   'transfer-encoding': 'chunked',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'cf-ray': '6ac9f7e1aff14528-TXL',
21 verbose headers   'cache-control': 'public, max-age=300',
21 verbose headers   etag: 'W/"a25a55081cb2b2240f629172425af517"',
21 verbose headers   'last-modified': 'Thu, 01 Jul 2021 06:50:38 GMT',
21 verbose headers   vary: 'accept-encoding, accept',
21 verbose headers   'cf-cache-status': 'MISS',
21 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
21 verbose headers   server: 'cloudflare',
21 verbose headers   'content-encoding': 'gzip' }
22 silly get cb [ 200,
22 silly get   { date: 'Thu, 11 Nov 2021 19:36:15 GMT',
22 silly get     'content-type': 'application/json',
22 silly get     'transfer-encoding': 'chunked',
22 silly get     connection: 'keep-alive',
22 silly get     'cf-ray': '6ac9f7e1aff14528-TXL',
22 silly get     'cache-control': 'public, max-age=300',
22 silly get     etag: 'W/"a25a55081cb2b2240f629172425af517"',
22 silly get     'last-modified': 'Thu, 01 Jul 2021 06:50:38 GMT',
22 silly get     vary: 'accept-encoding, accept',
22 silly get     'cf-cache-status': 'MISS',
22 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 silly get     server: 'cloudflare',
22 silly get     'content-encoding': 'gzip' } ]
23 verbose get saving @kba/makefile-parser to /home/xbert/.npm/registry.npmjs.org/_40kba_252fmakefile-parser/.cache.json
24 verbose makeDirectory /home/xbert/.npm creation not in flight; initializing
25 silly makeDirectory /home/xbert/.npm uid: 1000 gid: 1000
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule @kba/makefile-parser@0.0.6 checking installable status
39 silly cache add args [ '@kba/makefile-parser', null ]
40 verbose cache add spec @kba/makefile-parser
41 silly cache add parsed spec Result {
41 silly cache add   raw: '@kba/makefile-parser',
41 silly cache add   scope: '@kba',
41 silly cache add   name: '@kba/makefile-parser',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed @kba/makefile-parser@latest
43 verbose addNamed "latest" is being treated as a dist-tag for @kba/makefile-parser
44 info addNameTag [ '@kba/makefile-parser', 'latest' ]
45 silly mapToRegistry name @kba/makefile-parser
46 silly mapToRegistry scope (from package name) @kba
47 verbose mapToRegistry no registry URL found in name for scope @kba
48 silly mapToRegistry using default registry
49 silly mapToRegistry registry https://registry.npmjs.org/
50 silly mapToRegistry uri https://registry.npmjs.org/@kba%2fmakefile-parser
51 verbose addNameTag registry:https://registry.npmjs.org/@kba%2fmakefile-parser not in flight; fetching
52 verbose get https://registry.npmjs.org/@kba%2fmakefile-parser not expired, no request
53 silly addNameTag next cb for @kba/makefile-parser with tag latest
54 silly addNamed @kba/makefile-parser@0.0.6
55 verbose addNamed "0.0.6" is a plain semver version for @kba/makefile-parser
56 silly mapToRegistry name @kba/makefile-parser
57 silly mapToRegistry scope (from package name) @kba
58 verbose mapToRegistry no registry URL found in name for scope @kba
59 silly mapToRegistry using default registry
60 silly mapToRegistry registry https://registry.npmjs.org/
61 silly mapToRegistry uri https://registry.npmjs.org/@kba%2fmakefile-parser
62 verbose addRemoteTarball https://registry.npmjs.org/@kba/makefile-parser/-/makefile-parser-0.0.6.tgz not in flight; adding
63 verbose addRemoteTarball [ 'https://registry.npmjs.org/@kba/makefile-parser/-/makefile-parser-0.0.6.tgz',
63 verbose addRemoteTarball   '51d1967667690a2c8f13f1205b43a12e25b12e3e' ]
64 info retry fetch attempt 1 at 20:36:16
65 info attempt registry request try #1 at 20:36:16
66 http fetch GET https://registry.npmjs.org/@kba/makefile-parser/-/makefile-parser-0.0.6.tgz
67 http fetch 200 https://registry.npmjs.org/@kba/makefile-parser/-/makefile-parser-0.0.6.tgz
68 silly fetchAndShaCheck shasum 51d1967667690a2c8f13f1205b43a12e25b12e3e
69 verbose addTmpTarball /tmp/npm-15033-2b023c86/registry.npmjs.org/_40kba/makefile-parser/-/makefile-parser-0.0.6.tgz not in flight; adding
70 verbose addTmpTarball already have metadata; skipping unpack for @kba/makefile-parser@0.0.6
71 silly cache afterAdd @kba/makefile-parser@0.0.6
72 verbose afterAdd /home/xbert/.npm/@kba/makefile-parser/0.0.6/package/package.json not in flight; writing
73 verbose afterAdd /home/xbert/.npm/@kba/makefile-parser/0.0.6/package/package.json written
74 silly fetchNamedPackageData yargs
75 silly mapToRegistry name yargs
76 silly mapToRegistry using default registry
77 silly mapToRegistry registry https://registry.npmjs.org/
78 silly mapToRegistry uri https://registry.npmjs.org/yargs
79 verbose request uri https://registry.npmjs.org/yargs
80 verbose request no auth needed
81 info attempt registry request try #1 at 20:36:17
82 http request GET https://registry.npmjs.org/yargs
83 http 200 https://registry.npmjs.org/yargs
84 verbose headers { date: 'Thu, 11 Nov 2021 19:36:17 GMT',
84 verbose headers   'content-type': 'application/json',
84 verbose headers   'transfer-encoding': 'chunked',
84 verbose headers   connection: 'keep-alive',
84 verbose headers   'cf-ray': '6ac9f7f69fce4528-TXL',
84 verbose headers   age: '253',
84 verbose headers   'cache-control': 'public, max-age=300',
84 verbose headers   etag: 'W/"0ad32258c05e0a1c4a58389bf8c50454"',
84 verbose headers   'last-modified': 'Sat, 25 Sep 2021 21:19:25 GMT',
84 verbose headers   vary: 'accept-encoding, accept',
84 verbose headers   'cf-cache-status': 'HIT',
84 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
84 verbose headers   'x-amz-replication-status': 'PENDING',
84 verbose headers   server: 'cloudflare',
84 verbose headers   'content-encoding': 'gzip' }
85 silly get cb [ 200,
85 silly get   { date: 'Thu, 11 Nov 2021 19:36:17 GMT',
85 silly get     'content-type': 'application/json',
85 silly get     'transfer-encoding': 'chunked',
85 silly get     connection: 'keep-alive',
85 silly get     'cf-ray': '6ac9f7f69fce4528-TXL',
85 silly get     age: '253',
85 silly get     'cache-control': 'public, max-age=300',
85 silly get     etag: 'W/"0ad32258c05e0a1c4a58389bf8c50454"',
85 silly get     'last-modified': 'Sat, 25 Sep 2021 21:19:25 GMT',
85 silly get     vary: 'accept-encoding, accept',
85 silly get     'cf-cache-status': 'HIT',
85 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
85 silly get     'x-amz-replication-status': 'PENDING',
85 silly get     server: 'cloudflare',
85 silly get     'content-encoding': 'gzip' } ]
86 verbose get saving yargs to /home/xbert/.npm/registry.npmjs.org/yargs/.cache.json
87 verbose stack Error: Missing required argument #1
87 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
87 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
87 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
87 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
87 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
87 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
87 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
87 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
87 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
87 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
88 verbose cwd /home/xbert/unsortiert/arbeit/heyer/tools/ocrd_all
89 error Linux 4.15.0-72-generic
90 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@kba/makefile-parser"
91 error node v8.10.0
92 error npm  v3.5.2
93 error code EMISSINGARG
94 error typeerror Error: Missing required argument #1
94 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
94 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
94 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
94 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
94 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
94 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
94 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
94 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
94 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
94 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
95 error typeerror This is an error with npm itself. Please report this error at:
95 error typeerror     <http://github.com/npm/npm/issues>
96 verbose exit [ 1, true ]
```

</details>

**Comment by bertsky** [comment]
Note: I cannot even do `sudo npm i -g npm@latest` without error. (This is Ubuntu 18.04, where you can only get `npm` after updating to the newest `nodejs`.)
